# Generated by Django 3.1.4 on 2021-02-16 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data_employ',
        ),
    ]
