# Generated by Django 3.1.4 on 2021-02-16 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_data_employ'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data_employ',
        ),
    ]
