# Generated by Django 3.1.4 on 2021-03-01 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('component_id', models.AutoField(primary_key=True, serialize=False)),
                ('component_type', models.CharField(choices=[('P', 'PARTS'), ('C', 'CONSUMABLES')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Rfq',
            fields=[
                ('rfq_id', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(editable=False)),
                ('deadline', models.DateField()),
                ('targetdate', models.DateTimeField()),
                ('description', models.TextField()),
                ('attachment', models.URLField()),
                ('rfq_reach', models.CharField(choices=[('PVT', 'VENDOR_GROUP'), ('PUB', 'PUBLICLY')], max_length=3)),
                ('preference', models.CharField(choices=[('PRT', 'PRIORITY'), ('AOG', 'AOG'), ('NOR', 'NORMAL')], max_length=3)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('part_id', models.AutoField(primary_key=True, serialize=False)),
                ('part_name', models.CharField(max_length=50)),
                ('part_number', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('description', models.TextField()),
                ('manufacturer', models.CharField(default='others', max_length=100)),
                ('component_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfq.component')),
            ],
        ),
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('consumable_id', models.AutoField(primary_key=True, serialize=False)),
                ('part_number', models.CharField(max_length=20)),
                ('consumable_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('manufacturer', models.CharField(default='others', max_length=100)),
                ('component_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfq.component')),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='rfq_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rfq.rfq'),
        ),
    ]
